name: "Release Preparation"
description: "Template for tracking tasks needed for release preparation"
title: "[Release] - Release Preparation for vX.X.X"
labels: 
  - "release"
  - "task"
assignees: 
  - ""
body:
  - type: markdown
    attributes:
      value: |
        ## Release Preparation Checklist

        Please make sure to complete all of the following tasks for the release preparation. 
        Ensure that all items are checked off before proceeding to the release.

  - type: checkboxes
    id: pre_release
    attributes:
      label: "Pre-Release Tasks"
      description: "Tasks to be completed before starting the release process"
      options:
        - label: "Ensure README.md is updated"
        - label: "Ensure CHANGELOG.md is updated"
        - label: "Verify all dependencies are up to date"
        - label: "Ensure no critical bugs are present"

  - type: checkboxes
    id: release
    attributes:
      label: "Release Tasks"
      description: "Tasks to be completed during the release process"
      options:
        - label: "Make Stable Branch"
        - label: "Edit the release on GitHub"

  - type: checkboxes
    id: post_release
    attributes:
      label: "Post-Release Tasks"
      description: "Tasks to be completed after the release process"
      options:
        - label: "Bump up the version number in the pom.xml"
        - label: "Assign Issues to the next milestone"

  - type: input
    id: additional_notes
    attributes:
      label: "Additional Notes"
      description: "Add any other comments or tasks specific to this release."
      placeholder: "Enter additional release-related notes here"
