name: 'Build war file on PR from fork'

on:
  pull_request_target:
    branches: [main]
    types: 
      - labeled

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository != github.event.pull_request.head.repo.full_name && contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
    - run: |
        echo ${{github.repository}}
        echo ${{github.event.pull_request.head.repo.full_name}}}
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn package -DskipTests -B -P docker
    - name: Upload war file
      uses: actions/upload-artifact@v4
      with:
        name: airsonic-advanced
        path: airsonic-main/target/airsonic.war
        retention-days: 30
        overwrite: true
    