name: 'Build war file on PR'

on:
  pull_request:
    branches: [main]
    paths-ignore:
    - "**.md"
    - "*.txt"
    - ".github/**" 
    - "!.github/workflows/pr_build_war.yml"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == github.event.pull_request.head.repo.full_name
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn package -DskipTests -B -P docker
    - name: Upload war file
      uses: actions/upload-artifact@v4
      with:
        name: airsonic-advanced
        path: airsonic-main/target/airsonic.war
        retention-days: 30
        overwrite: true
    